### ISSUE TITLE
Document "New" Style Workbench Only Works With FreeCAD 17 and Greater 

### ISSUE THREAD

**Issue by gbroques** [FreeCAD/Workbench-Starterkit#11]
There's no mention anywhere on the **README** that this template doesn't work with FreeCAD 16 or earlier, and you need FreeCAD 17 or later.

It'd be nice if we could mention that you need to use the "old" style for supporting FreeCAD 16 or earlier.

**Comment by looooo** [comment]
https://github.com/FreeCAD/Workbench-Starterkit/commit/166c84d59f038bae34a39ce316b692a2882cf4aa

**Comment by gbroques** [comment]
thanks @looooo !
