### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by berndhahnebach** [FreeCAD/Workbench-Starterkit#5]
...
In the setup.py we do not have access to the library itself, so the `__vesion__` must be imported without the assumption that the package is installed. This can be done by running the file directly with `exec`.   
TODO: Is there any better way to do this?
...

should be `__version__` not `__vesion__` ?!?

**Comment by looooo** [comment]
Sry, never saw this. https://github.com/FreeCAD/Workbench-Starterkit/commit/f54892c4a2680bc01f4c93a18e4dd2dc9542a575
