### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by looooo** [FreeCAD/Workbench-Starterkit#8]
I don't know who is able to change the settings of this repo. Somehow I was disabled as an admin when transferring ownership of this repo. 

I would like to make this a template-repo which allows to start a new repo without the repo beeing a fork of this repo. I guess this will make it simpler to create a new workbench/module for freecad.

@yorikvanhavre maybe it's possible for you to add me back on the admin list or switch the template flag in the settings.

**Comment by looooo** [comment]
@kkremitzki maybe you can have a look at the settings and try to make this a template-repo?

**Comment by kkremitzki** [comment]
You should have admin rights now.
